#Configure this yaml file to get the desired behavior of the program
#NOTE: Do not change the name of this yaml file.

rawDataCSVPath: 'C:\Users\vjlat\Documents\Projects\CAN Data Handler\RawCANCSV'
extractedDataCSVPath: 'C:\Users\vjlat\Documents\Projects\CAN Data Handler\ExtractedCANCSV'
dbcFilePath: 'C:\Users\vjlat\Documents\Projects\CAN Data Handler\Input\CSS-Electronics-SAE-J1939-DEMO.dbc'
logFolderPath: 'C:\Users\vjlat\Documents\Projects\CAN Data Handler\Input\'

alerts:
  EngineSpeed:
    max: 5000
    min: 1000
    cutOff: 30
    filterOrder: 4 
  WheelBasedVehicleSpeed:
    max: 100
    min: 30
    cutOff: 3 
    filterOrder: 4