cc_library(
    name = "classify_obstacles_lib",
    srcs = ["classify_obstacles_lib.cpp"],
    hdrs = ["classify_obstacles_lib.hpp"],
    visibility = ["//classify_obstacles:__pkg__",
                  "//google_test:__pkg__"],
    deps = ["//custom_exception:custom_exception"],
)