#Configure this yaml file to get the desired behavior of the program
#NOTE: Do not change the name of this yaml file.

rawDataCSVPath: 'C:\Users\vjlat\Documents\Projects\CANDataHandler\RawCANCSV'
extractedDataCSVPath: 'C:\Users\vjlat\Documents\Projects\CANDataHandler\DecodedCANCSV'
dbcFilePath: 'C:\Users\vjlat\Documents\Projects\CANDataHandler\CANData\CSS-Electronics-SAE-J1939-DEMO.dbc'
watchFolderPath: 'C:\Users\vjlat\Documents\Projects\CANDataHandler\CANData\'
alertsFolderPath: 'C:\Users\vjlat\Documents\Projects\CANDataHandler\Alerts'

alerts:
  EngineSpeed:
    max: 5000
    min: 1000
    cutOff: 30
    filterOrder: 4 
  WheelBasedVehicleSpeed:
    max: 100
    min: 30
    cutOff: 3 
    filterOrder: 4