cc_library(
    name = "custom_exception",
    srcs = ["custom_exception.cpp"],
    hdrs = ["custom_exception.hpp"],
    visibility = ["//classify_obstacles:__pkg__",
                  "//classify_obstacles_lib:__pkg__",
                  "//google_test:__pkg__"],
)