cc_test(
  name = "classify_obstacles_test",
  size = "small",
  srcs = ["classify_obstacles_test.cpp"],
  deps = ["@com_google_googletest//:gtest_main",
          "//classify_obstacles_lib:classify_obstacles_lib",
          "//custom_exception:custom_exception"],
)